IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Countries')
BEGIN
	CREATE TABLE [dbo].[Countries]
	(
		co_id INT IDENTITY(1, 1) NOT NULL,
		co_countryName NVARCHAR(50) NOT NULL
	)
END
GO
IF OBJECT_ID('[dbo].[Countries]', 'PK') IS NULL
BEGIN
    ALTER TABLE [dbo].[Countries] 
    ADD CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED (co_id)
END
GO